server:
  port: 8080
spring:
  application:
    name: blog-app
  datasource:
    url:  jdbc:postgresql://localhost:5432/blog-app
    username: postgres
    password: postgres
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#project:
#  image: images/